/* ASE - Allegro Sprite Editor
 * Copyright (C) 2001-2010  David Capello
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 */

FOR_EACH_COMMAND(about)
FOR_EACH_COMMAND(advanced_mode)
FOR_EACH_COMMAND(autocrop_sprite)
FOR_EACH_COMMAND(background_from_layer)
FOR_EACH_COMMAND(canvas_size)
FOR_EACH_COMMAND(cel_properties)
FOR_EACH_COMMAND(change_color)
FOR_EACH_COMMAND(change_image_type)
FOR_EACH_COMMAND(check_updates)
FOR_EACH_COMMAND(clear)
FOR_EACH_COMMAND(close_all_files)
FOR_EACH_COMMAND(close_editor)
FOR_EACH_COMMAND(close_file)
FOR_EACH_COMMAND(color_curve)
FOR_EACH_COMMAND(configure_screen)
FOR_EACH_COMMAND(configure_tools)
FOR_EACH_COMMAND(convolution_matrix)
FOR_EACH_COMMAND(copy)
FOR_EACH_COMMAND(copy_cel)
FOR_EACH_COMMAND(crop_sprite)
FOR_EACH_COMMAND(cut)
FOR_EACH_COMMAND(deselect_mask)
FOR_EACH_COMMAND(despeckle)
FOR_EACH_COMMAND(donate)
FOR_EACH_COMMAND(duplicate_layer)
FOR_EACH_COMMAND(duplicate_sprite)
FOR_EACH_COMMAND(exit)
FOR_EACH_COMMAND(eyedropper)
FOR_EACH_COMMAND(film_editor)
FOR_EACH_COMMAND(flatten_layers)
FOR_EACH_COMMAND(flip)
FOR_EACH_COMMAND(frame_properties)
FOR_EACH_COMMAND(goto_first_frame)
FOR_EACH_COMMAND(goto_last_frame)
FOR_EACH_COMMAND(goto_next_frame)
FOR_EACH_COMMAND(goto_next_layer)
FOR_EACH_COMMAND(goto_previous_frame)
FOR_EACH_COMMAND(goto_previous_layer)
FOR_EACH_COMMAND(grid_settings)
FOR_EACH_COMMAND(invert_color)
FOR_EACH_COMMAND(invert_mask)
FOR_EACH_COMMAND(layer_from_background)
FOR_EACH_COMMAND(layer_properties)
FOR_EACH_COMMAND(load_mask)
FOR_EACH_COMMAND(make_unique_editor)
FOR_EACH_COMMAND(mask_all)
FOR_EACH_COMMAND(mask_by_color)
FOR_EACH_COMMAND(merge_down_layer)
FOR_EACH_COMMAND(move_cel)
FOR_EACH_COMMAND(new_file)
FOR_EACH_COMMAND(new_frame)
FOR_EACH_COMMAND(new_layer)
FOR_EACH_COMMAND(new_layer_set)
FOR_EACH_COMMAND(open_file)
FOR_EACH_COMMAND(options)
FOR_EACH_COMMAND(palette_editor)
FOR_EACH_COMMAND(paste)
FOR_EACH_COMMAND(play_animation)
FOR_EACH_COMMAND(preview_fit_to_screen)
FOR_EACH_COMMAND(preview_normal)
FOR_EACH_COMMAND(preview_tiled)
FOR_EACH_COMMAND(quick_reference)
FOR_EACH_COMMAND(record_screen)
FOR_EACH_COMMAND(redo)
FOR_EACH_COMMAND(refresh)
FOR_EACH_COMMAND(remove_cel)
FOR_EACH_COMMAND(remove_frame)
FOR_EACH_COMMAND(remove_layer)
FOR_EACH_COMMAND(replace_color)
FOR_EACH_COMMAND(reselect_mask)
FOR_EACH_COMMAND(rotate_canvas)
FOR_EACH_COMMAND(save_file)
FOR_EACH_COMMAND(save_file_as)
FOR_EACH_COMMAND(save_file_copy_as)
FOR_EACH_COMMAND(save_mask)
FOR_EACH_COMMAND(screen_shot)
FOR_EACH_COMMAND(select_file)
FOR_EACH_COMMAND(show_grid)
FOR_EACH_COMMAND(snap_to_grid)
FOR_EACH_COMMAND(split_editor_horizontally)
FOR_EACH_COMMAND(split_editor_vertically)
FOR_EACH_COMMAND(sprite_properties)
FOR_EACH_COMMAND(sprite_size)
FOR_EACH_COMMAND(switch_colors)
FOR_EACH_COMMAND(undo)
