name: Post Clang Tidy Comments
on:
  workflow_run:
    workflows: ["Clang Tidy Diff"]
    types:
    - completed

permissions:
  checks: write
  pull-requests: write

jobs:
  post-comments:
    runs-on: ubuntu-latest
    steps:
    - uses: ZedThree/clang-tidy-review/post@v0.20.1
      with:
        token: ${{ secrets.CLANG_TIDY_TOKEN }}
