name: Scheduled Merge with Upstream
on: 
  schedule:
    - cron: '0 16 * * 4'
    # scheduled for 00:00 every Monday
  workflow_dispatch:

jobs:
  sync-fork:
    runs-on: ubuntu-latest
    # Needs explicit permission to write to the repository
    permissions:
      contents: write
    steps:
      - uses: thiagokokada/merge-upstream@v1.0.2
        with:
          branch: main
