#!/usr/bin/sh

# Aseprite Desktop Integration Module
# Copyright (C) 2016  Gabriel Rauter
#
# Dual licensed under the MIT and GPL 2 licenses.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation or the MIT License
# (https://opensource.org/licenses/MIT).

if [ $# -ge 2 -a $# -lt 4 ]; then
  mkdir -p /tmp/Aseprite
  filename=${1//\//.}$RANDOM
  if [ $# -eq 2 ]; then
    aseprite -b --frame-range "0,0" $1 --sheet /tmp/Aseprite/$filename.png
  elif [ $# -eq 3 ]; then
    aseprite -b --frame-range "0,0" $1 --shrink-to "$3,$3" --sheet /tmp/Aseprite/$filename.png
  fi
  mkdir -p $(dirname "$2"); mv /tmp/Aseprite/$filename.png $2;
else
echo "Parameters for aseprite thumbnailer are: inputfile outputfile [size]"
fi
